name: Terimawa Bot Actions

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Aksi yang akan dijalankan (misal: get_qr)'
        required: true
        default: 'get_qr'
      bot_id:
        description: 'ID Bot WhatsApp (opsional)'
        required: false
      phone_number:
        description: 'Nomor telepon (opsional)'
        required: false
      # Input ini akan kita gunakan untuk mengirim ID unik dari PHP
      callback_extra_data:
        description: 'Data tambahan untuk dikirim balik ke callback, seperti session_id'
        required: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the bot script
        run: node bot.js
        env:
          # Mengambil kredensial dari GitHub Secrets
          TERIMAWA_USERNAME: ${{ secrets.TERIMAWA_USERNAME }}
          TERIMAWA_PASSWORD: ${{ secrets.TERIMAWA_PASSWORD }}
          
          # URL dan kunci rahasia untuk mengirim hasil ke shared hosting Anda
          CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
          CALLBACK_SECRET: ${{ secrets.CALLBACK_SECRET }}
          
          # Mengambil input dari pemicu workflow
          ACTION: ${{ github.event.inputs.action }}
          BOT_ID: ${{ github.event.inputs.bot_id }}
          PHONE_NUMBER: ${{ github.event.inputs.phone_number }}
          CALLBACK_EXTRA_DATA: ${{ github.event.inputs.callback_extra_data }}
