# Nama Workflow yang akan tampil di tab "Actions" di GitHub
name: Bot TerimaWA (Proxy Strategy)

# =========================================================================
# TRIGGER
# 'workflow_dispatch' berarti workflow ini hanya berjalan ketika dipicu
# secara manual atau melalui API.
# =========================================================================
on:
  workflow_dispatch:
    # Definisikan SEMUA input yang BISA diterima oleh workflow ini.
    inputs:
      action:
        description: 'Aksi yang dijalankan (get_qr, get_pairing_code, set_mode, set_blasting)'
        required: true
        type: string

      db_account_id:
        description: 'ID dari tabel whatsapp_accounts di database Anda'
        required: true
        type: string

      phone_number:
        description: 'Nomor HP untuk metode pairing code (contoh: 62812...)'
        required: false
        type: string
        
      terimawa_bot_id:
        description: 'ID Bot dari terimawa.com untuk dikelola'
        required: false
        type: string
        
      value:
        description: 'Nilai yang akan di-set (misal: mode "1", atau blast "1"/"0")'
        required: false
        type: string

# =========================================================================
# JOBS
# =========================================================================
jobs:
  run-bot-via-proxy:
    name: Mencoba via Proxy ${{ matrix.proxy }}
    runs-on: ubuntu-latest
    
    # =======================================================================
    # STRATEGI INTI: Menjalankan job yang sama untuk setiap proxy di daftar.
    # =======================================================================
    strategy:
      # Jika satu proxy gagal, jangan batalkan yang lain. Lanjutkan mencoba!
      fail-fast: false
      matrix:
        proxy: [
          # --- GANTI DAN TAMBAHKAN DAFTAR PROXY ANDA DI SINI ---

          # Ini proxy dari Perancis yang Anda temukan:
          '54.38.183.154:43258',

          # Contoh lain untuk memperbesar peluang (cari yang baru untuk hasil terbaik):
          '177.44.240.51:8080',  # Brazil
          '103.152.4.88:80',     # Indonesia
          '181.112.193.186:999', # Bolivia
          '45.228.13.194:999',  # Paraguay
          '190.104.14.2:8080',   # Argentina
          '81.91.137.130:8080'   # Kenya

          # Tambahkan lebih banyak proxy di sini...
        ]
        
    # Definisikan environment variables yang akan tersedia untuk bot.js
    env:
      # Kredensial Login TerimaWA (dari Secrets)
      TERIMAWA_USERNAME: ${{ secrets.TERIMAWA_USERNAME }}
      TERIMAWA_PASSWORD: ${{ secrets.TERIMAWA_PASSWORD }}
      CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      CALLBACK_SECRET: ${{ secrets.CALLBACK_SECRET }}
      
      # Meneruskan semua input dari trigger ke environment skrip
      ACTION: ${{ github.event.inputs.action }}
      DB_ACCOUNT_ID: ${{ github.event.inputs.db_account_id }}
      PHONE_NUMBER: ${{ github.event.inputs.phone_number }}
      TERIMAWA_BOT_ID: ${{ github.event.inputs.terimawa_bot_id }}
      VALUE: ${{ github.event.inputs.value }}
      
      # Variabel baru untuk meneruskan proxy dari matrix ke bot.js
      PROXY_SERVER: ${{ matrix.proxy }}

    # Urutan langkah-langkah yang akan dijalankan
    steps:
      - name: 1. Checkout Repositori
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 3. Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 4. Install Dependencies
        run: npm install
        
      - name: 5. Jalankan Skrip Bot via Proxy
        # Terus lanjutkan bahkan jika skrip ini gagal, agar kita bisa melihat hasil job lain
        continue-on-error: true 
        run: node bot.js
