name: Run Terimawa Python Bot

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # --- LANGKAH TAMBAHAN UNTUK MEMBERSIHKAN CACHE ---
      - name: Clear Playwright cache
        run: rm -rf ~/.cache/ms-playwright

      - name: Install Playwright browsers and dependencies
        run: playwright install --with-deps

      - name: Run the bot script
        # --- PASTIKAN NAMA FILE DI SINI SAMA DENGAN NAMA FILE PYTHON ANDA ---
        run: python run_bot.py
        env:
          TERIMAWA_USERNAME: ${{ secrets.TERIMAWA_USERNAME }}
          TERIMAWA_PASSWORD: ${{ secrets.TERIMAWA_PASSWORD }}
